### PR TITLE
Adding support for fontawesome

### PR DESCRIPTION
**Pull request by gowthamgts**

### CODE REVIEW

**Comment by joysoft33** [comment]
Hi mainteners, is it possible to merge this PR please ?

**Comment by gowthamgts** [comment]
ping @abdulk1

**Comment by joysoft33** [comment]
Is there anybody here ? Your module is a great one but incompatible with Bootstrap 4 who don't use glyph icons anymore. Can you take one minute to merge this simple and useful PR please ?

**Comment by gowthamgts** [comment]
@joysoft33 You can use this package: https://www.npmjs.com/package/@chaitanya11/ng-datatable which is a cloned version with Feather and Font Awesome icon support.

**Comment by joysoft33** [comment]
Thank you !! 😊😊

**Pull request merged**
